// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTwVCm5J_-eFzYGc8jezkqsTqpBzeb180',
    appId: '1:292480032080:web:bb4f668fbfd0d56c0ea055',
    messagingSenderId: '292480032080',
    projectId: 'to-do-app-f7b26',
    authDomain: 'to-do-app-f7b26.firebaseapp.com',
    storageBucket: 'to-do-app-f7b26.appspot.com',
    measurementId: 'G-HLYRVWLVLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvRGHS-wvl6tAL2o22sWtpniTvDEX51GA',
    appId: '1:292480032080:android:e1eba4ddcdfc495d0ea055',
    messagingSenderId: '292480032080',
    projectId: 'to-do-app-f7b26',
    storageBucket: 'to-do-app-f7b26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1MU3NFhT9I71_tYC9f-KH2CX7fJmM2QM',
    appId: '1:292480032080:ios:0e77077913a619830ea055',
    messagingSenderId: '292480032080',
    projectId: 'to-do-app-f7b26',
    storageBucket: 'to-do-app-f7b26.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1MU3NFhT9I71_tYC9f-KH2CX7fJmM2QM',
    appId: '1:292480032080:ios:0e77077913a619830ea055',
    messagingSenderId: '292480032080',
    projectId: 'to-do-app-f7b26',
    storageBucket: 'to-do-app-f7b26.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTwVCm5J_-eFzYGc8jezkqsTqpBzeb180',
    appId: '1:292480032080:web:59b589784938d2d90ea055',
    messagingSenderId: '292480032080',
    projectId: 'to-do-app-f7b26',
    authDomain: 'to-do-app-f7b26.firebaseapp.com',
    storageBucket: 'to-do-app-f7b26.appspot.com',
    measurementId: 'G-MC0LWTN431',
  );
}
